// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: todogrpc/todogrpc.proto

package todogrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTodo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *NewTodo) Reset() {
	*x = NewTodo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todogrpc_todogrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTodo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTodo) ProtoMessage() {}

func (x *NewTodo) ProtoReflect() protoreflect.Message {
	mi := &file_todogrpc_todogrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTodo.ProtoReflect.Descriptor instead.
func (*NewTodo) Descriptor() ([]byte, []int) {
	return file_todogrpc_todogrpc_proto_rawDescGZIP(), []int{0}
}

func (x *NewTodo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewTodo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TodoName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *TodoName) Reset() {
	*x = TodoName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todogrpc_todogrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoName) ProtoMessage() {}

func (x *TodoName) ProtoReflect() protoreflect.Message {
	mi := &file_todogrpc_todogrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoName.ProtoReflect.Descriptor instead.
func (*TodoName) Descriptor() ([]byte, []int) {
	return file_todogrpc_todogrpc_proto_rawDescGZIP(), []int{1}
}

func (x *TodoName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todogrpc_todogrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_todogrpc_todogrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_todogrpc_todogrpc_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Todo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Todo) Reset() {
	*x = Todo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todogrpc_todogrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todogrpc_todogrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todogrpc_todogrpc_proto_rawDescGZIP(), []int{3}
}

func (x *Todo) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Todo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Todo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RepeatedTodo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo []*Todo `protobuf:"bytes,1,rep,name=Todo,proto3" json:"Todo,omitempty"`
}

func (x *RepeatedTodo) Reset() {
	*x = RepeatedTodo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todogrpc_todogrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedTodo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedTodo) ProtoMessage() {}

func (x *RepeatedTodo) ProtoReflect() protoreflect.Message {
	mi := &file_todogrpc_todogrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedTodo.ProtoReflect.Descriptor instead.
func (*RepeatedTodo) Descriptor() ([]byte, []int) {
	return file_todogrpc_todogrpc_proto_rawDescGZIP(), []int{4}
}

func (x *RepeatedTodo) GetTodo() []*Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

var File_todogrpc_todogrpc_proto protoreflect.FileDescriptor

var file_todogrpc_todogrpc_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x67,
	0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x35, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x42, 0x0a, 0x04, 0x54, 0x6f,
	0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x32,
	0x0a, 0x0c, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x22,
	0x0a, 0x04, 0x54, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74,
	0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x04, 0x54, 0x6f,
	0x64, 0x6f, 0x32, 0x94, 0x02, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x43, 0x52, 0x55, 0x44, 0x12,
	0x32, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x11, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x64, 0x6f,
	0x1a, 0x0f, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x22, 0x00, 0x12,
	0x2f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x12, 0x2e, 0x74, 0x6f, 0x64,
	0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0e,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x12,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x4e, 0x61,
	0x6d, 0x65, 0x1a, 0x0f, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x6f, 0x64, 0x6f, 0x12, 0x11, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e,
	0x65, 0x77, 0x54, 0x6f, 0x64, 0x6f, 0x1a, 0x0f, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x62, 0x78, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x2d, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x2d, 0x61, 0x72, 0x63, 0x68, 0x2f,
	0x74, 0x6f, 0x64, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todogrpc_todogrpc_proto_rawDescOnce sync.Once
	file_todogrpc_todogrpc_proto_rawDescData = file_todogrpc_todogrpc_proto_rawDesc
)

func file_todogrpc_todogrpc_proto_rawDescGZIP() []byte {
	file_todogrpc_todogrpc_proto_rawDescOnce.Do(func() {
		file_todogrpc_todogrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_todogrpc_todogrpc_proto_rawDescData)
	})
	return file_todogrpc_todogrpc_proto_rawDescData
}

var file_todogrpc_todogrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_todogrpc_todogrpc_proto_goTypes = []interface{}{
	(*NewTodo)(nil),       // 0: todogrpc.NewTodo
	(*TodoName)(nil),      // 1: todogrpc.TodoName
	(*Error)(nil),         // 2: todogrpc.Error
	(*Todo)(nil),          // 3: todogrpc.Todo
	(*RepeatedTodo)(nil),  // 4: todogrpc.RepeatedTodo
	(*emptypb.Empty)(nil), // 5: google.protobuf.Empty
}
var file_todogrpc_todogrpc_proto_depIdxs = []int32{
	3, // 0: todogrpc.RepeatedTodo.Todo:type_name -> todogrpc.Todo
	0, // 1: todogrpc.TodoCRUD.CreateTodo:input_type -> todogrpc.NewTodo
	5, // 2: todogrpc.TodoCRUD.GetAll:input_type -> google.protobuf.Empty
	1, // 3: todogrpc.TodoCRUD.GetTodo:input_type -> todogrpc.TodoName
	1, // 4: todogrpc.TodoCRUD.DeleteTodo:input_type -> todogrpc.TodoName
	0, // 5: todogrpc.TodoCRUD.UpdateTodo:input_type -> todogrpc.NewTodo
	2, // 6: todogrpc.TodoCRUD.CreateTodo:output_type -> todogrpc.Error
	4, // 7: todogrpc.TodoCRUD.GetAll:output_type -> todogrpc.RepeatedTodo
	3, // 8: todogrpc.TodoCRUD.GetTodo:output_type -> todogrpc.Todo
	2, // 9: todogrpc.TodoCRUD.DeleteTodo:output_type -> todogrpc.Error
	2, // 10: todogrpc.TodoCRUD.UpdateTodo:output_type -> todogrpc.Error
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_todogrpc_todogrpc_proto_init() }
func file_todogrpc_todogrpc_proto_init() {
	if File_todogrpc_todogrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todogrpc_todogrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTodo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todogrpc_todogrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todogrpc_todogrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todogrpc_todogrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Todo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todogrpc_todogrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedTodo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todogrpc_todogrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todogrpc_todogrpc_proto_goTypes,
		DependencyIndexes: file_todogrpc_todogrpc_proto_depIdxs,
		MessageInfos:      file_todogrpc_todogrpc_proto_msgTypes,
	}.Build()
	File_todogrpc_todogrpc_proto = out.File
	file_todogrpc_todogrpc_proto_rawDesc = nil
	file_todogrpc_todogrpc_proto_goTypes = nil
	file_todogrpc_todogrpc_proto_depIdxs = nil
}
